### ISSUE TITLE
Doesn't work. Nothing happens.

### ISSUE THREAD

**Issue by inigopascall** [cacciaresi/ulauncher-asana#3]
I'm using Pop!_OS 22.04 / Ulancher v5.15.3

I have created a personal access token in Asana (50 chars, starts with a single digit followed by a forward-slash) which is registered in the /apps section of my Asana account)

I have installed the extension, and pasted the same token into Ulancher, under Extensions > Asana > API Token.

I have quit and restarted Ulauncher.

Opening UL and typing `a ` opens the menu "create a task", "search projects" etc, but nothing happens with any of these options-- no indication that it is connected with my account in any way. I can only assume the connection/authorization has failed for some reason. I've no idea if any errors are logged, or where to look for them (?)

Pity, I was really looking forward to using what seemed like a great extension :/

**Comment by inigopascall** [comment]
I guess this project is dead, sadly :(

**Comment by cacciaresi** [comment]
> I guess this project is dead, sadly :(

@inigopascall The project was dead but together we have revived it ;) See here https://github.com/cacciaresi/ulauncher-asana/pull/4
